config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/')
  get '/about', to: redirect('#/about')
  get '/portfolio-commercial', to: redirect('#/portfolio-commercial')
  get '/portfolio-residential', to: redirect('#/portfolio-residential')
  get '/pricing', to: redirect('#/pricing')
  get '/how-it-works', to: redirect('#/how-it-works')
  get '/information', to: redirect('#/information')
  get '/terms', to: redirect('#/terms')
  get '/contact', to: redirect('#/contact')
  get '/career', to: redirect('#/career')

  devise_for :users, class_name: "Admin::User"

  namespace :api do
    resources :home_slides, only: [:index]
    resources :commercial_slides, only: [:index]
    resources :residential_slides, only: [:index]
  end
  
  namespace :admin do
    get '/', to: redirect('/admin/dashboard')
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :home_slides, only: [:index, :new, :create]
    resources :commercial_slides, only: [:index, :new, :create]
    resources :residential_slides, only: [:index, :new, :create]

    namespace :api do
      # Routes for Admin Home Slides
      resources :home_slides, only: [:index, :destroy]
      put '/home_slides', to: 'home_slides#update_order'

      # Routes for Admin Commercial Slides
      resources :commercial_slides, only: [:index, :destroy]
      put '/commercial_slides', to: 'commercial_slides#update_order'

      # Routes for Admin Residential Slides
      resources :residential_slides, only: [:index, :destroy]
      put '/residential_slides', to: 'residential_slides#update_order'
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/commercial_slide.rb
class CommercialSlide < ActiveRecord::Base
  include Imageable
  include Rankable
end

app/models/home_slide.rb
class HomeSlide < ActiveRecord::Base
  include Imageable
  include Rankable
end

app/models/residential_slide.rb
class ResidentialSlide < ActiveRecord::Base
  include Imageable
  include Rankable
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    http_basic_authenticate_with name: "carpentry.sg@gmail.com", password: "zunthe23"
    # before_action :authenticate_admin_user!
    layout 'admin'

    private
      def authenticate_admin_user!
        
      end
  end
end

app/controllers/admin/api/api_controller.rb
module Admin
  module Api
    class ApiController < AdminController
      before_filter :set_default_response_format

      private
        def set_default_response_format
          request.format = :json
        end
    end
  end
end

app/controllers/admin/api/home_slides_controller.rb
module Admin
  module Api
    class HomeSlidesController < Admin::Api::SlidesController
      set_resource :home_slide
    end
  end
end

app/controllers/admin/api/slides_controller.rb
module Admin
  module Api
    class SlidesController < Admin::Api::ApiController

      # Macros
      def self.set_resource(resource_name)
        define_method(:resource) do 
          "#{resource_name.to_s}" || 'home_slide' # Default value
        end
      end

      def resource_model
        eval(resource.camelize)
      end

      # Controller Methods
      def index
        @slides = resource_model.all.order(:rank)
        render 'admin/shared/slides'
      end

      def update_order
        if params[:_json]
          slides = params.require(:_json)

          if resource_model.update_all_ranks(slides)
            render json: { success: true }
          else
            render json: { success: false }
          end
        else
          render json: { success: true }
        end
      end

      def destroy
        slide = resource_model.find_by(id: params.require(:id))
        if slide.destroy
          render json: { success: true }
        else
          render json: { success: false }
        end
      end
    end
  end
end

app/controllers/admin/commercial_slides_controller.rb
module Admin
  class CommercialSlidesController < Admin::SlidesController
    set_resource :commercial_slide
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < Admin::AdminController
    def index
      @home_slides_count = ::HomeSlide.all.count
      @commercial_slides_count = ::CommercialSlide.all.count
      @residential_slides_count = ::ResidentialSlide.all.count
    end
  end
end

app/controllers/admin/home_slides_controller.rb
module Admin
  class HomeSlidesController < Admin::SlidesController
    set_resource :home_slide
  end
end

app/controllers/admin/residential_slides_controller.rb
module Admin
  class ResidentialSlidesController < Admin::SlidesController
    set_resource :residential_slide
  end
end

app/controllers/admin/slides_controller.rb
module Admin
  class SlidesController < Admin::AdminController

    # Macros
    def self.set_resource(resource_name)
      define_method(:resource) do 
        "#{resource_name.to_s}" || 'home_slide' # Default value
      end
    end


    # Helper Methods
    helpers = %w(slide_type index_path new_path resource resource_model)
    hide_action(*helpers)
    helper_method(*helpers)

    def slide_type
      resource.split("_").first.capitalize
    end

    def index_path
      "/admin/#{resource}s"
    end

    def new_path
      "/admin/#{resource}s/new"
    end

    def resource_model
      eval(resource.camelize)
    end



    # Controller Actions
    def index
      render 'admin/shared/index_slides'
    end

    def new
      @slide = resource_model.new
      render 'admin/shared/new_slide'
    end

    def create
      @slide = resource_model.new(slide_params)
      @slide.set_rank

      if @slide.save
        flash[:notice] = "Sucessful."
        redirect_to index_path
      else
        flash[:error] = "There is a problem with your upload. Please try again."
        render :new
      end
    end

    private
      def slide_params
        params.require(resource.to_sym).permit!
      end

  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    before_filter :set_default_response_format

    private
      def set_default_response_format
        request.format = :json
      end
  end
end

app/controllers/api/commercial_slides_controller.rb
module Api
  class CommercialSlidesController < Api::ApiController

    def index
      @slides = CommercialSlide.all.order(:rank)
      render 'admin/shared/slides'
    end
    
  end
end

app/controllers/api/home_slides_controller.rb
module Api
  class HomeSlidesController < Api::ApiController

    def index
      @slides = HomeSlide.all.order(:rank)
      render 'admin/shared/slides'
    end
    
  end
end

app/controllers/api/residential_slides_controller.rb
module Api
  class ResidentialSlidesController < Api::ApiController

    def index
      @slides = ResidentialSlide.all.order(:rank)
      render 'admin/shared/slides'
    end
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def datetime_formatter(datetime)
    if datetime
      time_zone = current_user.try(:time_zone) || Time.zone.name
      datetime.in_time_zone(time_zone).strftime("%d %b %Y,%l:%M %p (%Z%z)")  
    end
  end

  def menu_active(path)
    return 'active' if request.path == path
  end
end

app/views/admin/shared/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>Singapore Carpentry | Admin Portal</title>

<%= stylesheet_link_tag 'admin', media: 'all' %>
<%= csrf_meta_tags %>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/admin/shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= admin_dashboard_path %>">Singapore Carpentry | Admin Portal</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="mailto:carpentry.sg@gmail.com"><i class="fa fa-user fa-fw"></i> SG Carpentry User</a></li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <%= image_tag 'logo-dark.png', alt: 'Singapore Carpentry Logo', style: "margin: 0 auto;" %>
                </li>
                <li><a class="<%= menu_active(admin_dashboard_path) %>" href="<%= admin_dashboard_path %>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a></li>
                <li><a class="<%= menu_active(admin_home_slides_path) %>" href="<%= admin_home_slides_path %>"><i class="fa fa-home fa-fw"></i> Home Portfolio</a></li>
                <li><a class="<%= menu_active(admin_commercial_slides_path) %>" href="<%= admin_commercial_slides_path %>"><i class="fa fa-building-o fa-fw"></i> Commercial Portfolio</a></li>
                <li><a class="<%= menu_active(admin_residential_slides_path) %>" href="<%= admin_residential_slides_path %>"><i class="fa fa-pagelines fa-fw"></i> Residential Portfolio</a></li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/admin/shared/index_slides.html.erb
<div class="portfolio-index" ng-app="sortableApp" ng-controller="MainCtrl">
  <input id="slide-model" type="hidden" value="<%= slide_type %>Slides">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Manage Portfolio: <%= slide_type %></h1>
    </div>
  </div>

  <div class="row action-section">
    <div class="col-lg-12">
      <%= link_to new_path, class: "btn btn-outline btn-primary btn-lg" do %>
        <i class="fa fa-plus-circle"></i> Add <%= slide_type %> Slide
      <% end %>
      <a ng-click="updateOrder()" class="btn btn-outline btn-primary btn-lg">
        <i class="fa fa-refresh"></i> Update Order
      </a>
    </div>
  </div>

  <div class="row list-section">
    <div class="col-lg-12">

      <div class="panels" ui-sortable="sortableOptions" ng-model="slides">
        <div class="panel panel-info" ng-repeat="slide in slides">
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-1 icon-col">
                  <i class="fa fa-arrows move"></i>
                </div>
                <div class="col-lg-3 image-col">
                  <img src="{{slide.image_thumb_url}}">
                </div>
                <div class="col-lg-6 info-col">
                  <p><strong>{{ slide.file_name }}</strong> <small>{{ slide.created_at }}</small></p>
                  <a href="{{slide.image_original_url}}" target="_window" class="btn btn-outline btn-sm btn-info"><i class="fa fa-search-plus"></i> View Original Size</a>
                  <a href="{{slide.image_screen_url}}" target="_window" class="btn btn-outline btn-sm btn-info"><i class="fa fa-search-plus"></i> View Screen Size</a>
                </div>
                <div class="col-lg-2 delete-col">
                  <a ng-click="destroySlide(slide)" target="_window" class="btn btn-outline btn-sm btn-danger"><i class="fa fa-trash-o"></i> Delete</a>
                </div>
              </div>
                
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :page_scripts do %>
  <%= javascript_include_tag 'sortableApp' %>
<% end %>

app/views/admin/shared/new_slide.html.erb
<div class="portfolio-new">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Manage Portfolio: <%= @slide_type %> | New Slide</h1>
    </div>
  </div>

  <div class="row form">
    <div class="col-lg-6">
      <div class="panel panel-info">
        <%= bootstrap_form_for(@slide, url: index_path, html: { multipart: true }) do |f| %>
          <div class="panel-heading">
              Add a new <%= slide_type %> Slide
          </div>
          <div class="panel-body">
            <%= f.file_field :image, required: true %>  
          </div>
          <div class="panel-footer">
              <%= f.submit "Add Slide" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render 'admin/shared/head' %>
</head>
<body>
  <div id="wrapper">

    <%= render 'admin/shared/nav' %>

    <div id="page-wrapper">
      <%= yield %>
    </div>

  </div>

  <%= javascript_include_tag 'admin' %>
  <%= yield :page_scripts %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Singapore Carpentry</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>